# Generated by Django 5.2.5 on 2025-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
    ]
