# Generated by Django 5.2.5 on 2025-09-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_is_translated'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='تایتیل وارد نشده است !', max_length=250),
        ),
    ]
