# Generated by Django 5.2.5 on 2025-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='عنوان وارد نشده است! محتوا را مشاهده کنید ...', max_length=250),
        ),
    ]
